export const SELECTED_CLASS_NAME = "CONTENT_SAVER_SELECTED"
export const PARTIAL_INVALID_SELECTED_CLASS_NAME = "CONTENT_SAVER_PARTIAL_INVALID_SELECTED"
export const INVALID_SELECTED_CLASS_NAME = "CONTENT_SAVER_INVALID_SELECTED"
export const TOGGLED_ON_HIGHLIGHT_CLASS_NAME = "CONTENT_SAVER_HIGHLIGHT"
export const TOGGLED_OFF_HIGHLIGHT_CLASS_NAME = "CONTENT_SAVER_INACTIVE_HIGHLIGHT"
export const TOGGLE_KEY_PRESSES = [" ", "T"]
export const SOFT_TOGGLE_KEYCODE = "`"