

export const DELETE_DOWNLOAD_ITEM = "DELETE_DOWNLOAD_ITEM"
export const CANCEL_DOWNLOAD = "CANCEL_DOWNLOAD"
export const ADHOC_DOWNLOAD = "ADHOC_DOWNLOAD"
export const DOWNLOAD_ALL = "DOWNLOAD_ALL_BATCHES"
export const DOWNLOAD_ZIP_FILE = "DOWNLOAD_ZIP_FILE"
export const ACTION_DOWNLOAD = "ACTION_DOWNLOAD"